name: release
permissions:
  contents: read
  id-token: write
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          scope: '@contentgrid'
          package-manager-cache: false
      - run: |
          corepack enable
          yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish
        run:
          yarn lerna publish "${{ github.ref_name }}" --yes --no-push --no-git-tag-version --force-publish
